### ISSUE TITLE
Build Setup

### ISSUE THREAD

**Issue by mcwhittemore** [serverless/dashboard#1]
I might be able to get to this tomorrow, but I just wanted to document what needed to be done. If someone starts this, please comment saying so.
- [ ] React
- [ ] Build Tool (browserify?)
- [ ] Babel
- [ ] Flux or no flux

**Comment by ac360** [comment]
Nice :+1: 

@mcwhittemore Do you think Babel will introduce too much complexity or will it yield significant benefits?

**Comment by mcwhittemore** [comment]
For a build I lean towards browserify for the build tool. Its one of the most straight forward and while it lacks some bells and whistles, anyone who joins the project will have a rather small learning curve.

Per @SOSANA comments in https://github.com/jaws-framework/JAWS/issues/240#issuecomment-148757249 flux can be devisive. I've worked with shelf rolled flux via facebook's dispatcher and [alt](https://github.com/goatslacker/alt) they have their ups and down. I think this is a good idea, but picking something that isn't too intimating is key.

**Comment by mcwhittemore** [comment]
@ac360 I think babel is normal now.

**Comment by mcwhittemore** [comment]
Also, its part of facebooks setup for React now: https://facebook.github.io/react/docs/getting-started.html#offline-transform

**Comment by ac360** [comment]
@mcwhittemore Alright, let's go with Babel.  I'm good with Browserify too, we're already heavy users of it in JAWS core.  Can't speak to Flux.

**Comment by ecwyne** [comment]
@ac360 I've personally just started looking into react and flux. This video is honestly what got me excited about it all (from the creator of redux) the flux framework ["all the cool kids are using"](https://github.com/jaws-framework/JAWS/issues/240#issuecomment-148756753)

https://www.youtube.com/watch?v=xsSnOQynTHs

The workflow that this enables is CRAZY awesome

**Comment by ac360** [comment]
Eric Wyne in the house!  I will check out the video.  @mcwhittemore is a cool kid too, so the pattern holds.

**Comment by marclar** [comment]
Definitely use Flux. Slight learning curve but the benefits of organizing the data flow can't be overestimated.

**Comment by mcwhittemore** [comment]
So, I think I'm going to have to drop out here. I want to help but I also want to ship a few side projects and I don't think I can do both right now. Sorry.

**Comment by kevinold** [comment]
I can help with a React and Redux setup

**Comment by DavidWells** [comment]
Babel + webpack FTW!!!!!

Excited for whats coming next. Closing this issue

**Comment by SOSANA** [comment]
@DavidWells what's coming next?
