### ISSUE TITLE
V0.0.1 – Can't create new service

### ISSUE THREAD

**Issue by ac360** [serverless/dashboard#15]
Error while trying to create a new service immediately after fresh install: 

```
(index):109 Failed to create the service(anonymous function) @ (index):109
(index):5 spawn args Array[3]
(index):109 Failed to create the service(anonymous function) @ (index):109
```

Unfortunately, I don't have much more information than that.

**Comment by DavidWells** [comment]
Fresh install from where? The repo or the packaged asset in s3?

That args console `(index):5 spawn args Array[3]` has info in it.

**Comment by ac360** [comment]
https://s3-us-west-2.amazonaws.com/assets.dashboard/Serverless.app.0.0.1.zip

I checked the `(index):5 spawn args Array[3]` but didn't see anything of value to the issue in there.  Is there something specific that you could use from that?

**Comment by ac360** [comment]
This may likely be the same `minimist` issue.
