### ISSUE TITLE
V0.0.1 – Cannot perform any actions

### ISSUE THREAD

**Issue by ac360** [serverless/dashboard#16]
I'm unable to perform any actions with **any** pre-existing service due to the following error:

```
serverless deploy --stage dev --region us-east-1  Error --------------------------------------------------  
Cannot find module 'minimist'  For debugging logs, run again after setting SLS_DEBUG env var.  
Get Support -------------------------------------------- 
Docs: docs.serverless.com Bugs: github.com/serverless/serverless/issues  
Please report this error. We think it might be a bug.  
Your Environment Information ----------------------------- 
OS: darwin 
Node Version: 6.6.0 
Serverless Version: 1.1.0 
```

**Comment by ac360** [comment]
Other notes:

* When I clone the dashboard, npm install, and run it, this is not an issue.  It's only with the packaged application.
* We might not be the only ones: 
  * https://github.com/wireapp/wire-desktop/issues/95

**Comment by DavidWells** [comment]
After you run `npm run package` the build `.app` is throwing these errors?

**Comment by ac360** [comment]
@DavidWells Nope, just checked.

**Comment by nikgraf** [comment]
@ac360 is this resolved now? can we close the issue?

**Comment by DavidWells** [comment]
fixed
