### ISSUE TITLE
Onboarding flow not possible on a Macbook with 13inch screen

### ISSUE THREAD

**Issue by nikgraf** [serverless/dashboard#20]
It's not high enough to show the button.

<img width="802" alt="screen shot 2016-11-08 at 12 17 17" src="https://cloud.githubusercontent.com/assets/223045/20097189/79ec589c-a5ad-11e6-9389-7d8cc451c3c4.png">

**Comment by DavidWells** [comment]
Taking the steve jobs approach here... Time for you to buy a bigger computer. ٩◔‿◔۶

j/k I will fix
