### ISSUE TITLE
Feature Request: Create folder for new services

### ISSUE THREAD

**Issue by ac360** [serverless/dashboard#31]
Please create a folder using the `--path` option upon creating a new service.  

Installing in the CWD is unexpected behavior IMO, and it causes me to have to check the CWD and clean it out before I can use the Dashboard, which isn't the right experience.

**Comment by nikgraf** [comment]
@ac360 do you mean somebody should select a directory and then we have another input field for the --path? Should it be optional or always like this?

**Comment by ac360** [comment]
@nikgraf Yes, but no additional input field is needed.  Everything works exactly the same, but `--path` is used instead of `--name` in the `sls create` command:

* User selects a directory (where another folder for their service will be created)
* User enters in the `name` field that already exists.
* User selects template and hits `create`
* The Framework then runs `sls create --template [TEMPLATE] --path [NAME]`.  Which creates a folder using the `name` they entered.

**Comment by nikgraf** [comment]
@ac360 fixed the issue, let me know if that's what you have expected
