### ISSUE TITLE
Include configuration to enable/disable AWS Lambda event and response collection

### ISSUE THREAD

**Issue by austencollins** [serverless/dashboard#32]
Include configuration to enable/disable AWS Lambda event and response collection.

I would expect this to be opt out by default, for users' production stages.

**Comment by medikoo** [comment]
Support for `disableRequestResponseMonitoring` in `SLS_OTEL_USER_SETTINGS` was brought with https://github.com/serverless/runtime/pull/39 (released with v0.2.19).

Production mode, with which it'll be on by default is still pending

**Comment by medikoo** [comment]
Closing, as we've decided to collect them only in dev mode (as opt-out)
