### ISSUE TITLE
Show finder / explorer window when clicking on "open directory"

### ISSUE THREAD

**Issue by pmuens** [serverless/dashboard#45]
- [x] I have searched the [issues](https://github.com/serverless/dashboard/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS X 10.12.1
- **Serverless.app version**: 0.0.5

## Issue

The "open directory" button works but it would be great if the window which will be opened would pop up / over the dashboard app (right now it opens in the background which might confuse users).

**Comment by DavidWells** [comment]
Fixed for next release. 

Needed `showItemInFolder ` instead of `openItem` from the electron shell

https://github.com/electron/electron/blob/master/docs/api/shell.md
