### ISSUE TITLE
Rename "Delete" to "Remove from list"

### ISSUE THREAD

**Issue by pmuens** [serverless/dashboard#50]
- [x] I have searched the [issues](https://github.com/serverless/dashboard/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS X 10.12.1
- **Serverless.app version**: 0.0.5

## Issue

The "Delete" button in the service list is a little bit misleading as it won't remove the service from the hard drive (I remember that a previous version had a note that the service will remain in the HDD). It might be better to rename it to "Remove from list" or something similar.

**Comment by DavidWells** [comment]
Indeed! Updated for next release
