### ISSUE TITLE
Firehose serverless_logs-firehose not found

### ISSUE THREAD

**Issue by oddity-code** [serverless/dashboard#845]
I've created an account in serverless console and integrated there an AWS account according to the manual.

Account appears in the console and the status of integration is "Complete".
The account didn't have any Lambda functions at the moment of integration.

After that I've deployed a new serverless stack, got a link to the console for the stack in the CLI. Followed a link and got a message, that the stack needs to be instrumented, so I allowed at, but got an error:
`[Instrument By Mode] Could not deliver test message to specified Firehose stream. Firehose serverless_logs-firehose not found under account ACCOUNT_ID.`

Same for "dev" mode instrumentation.

Checking the resources in Firehouse I can confirm, that there is no stream with name "serverless_logs-firehose" present.
Also when I check the "Serverless-Inc-Role-Stack" Cloudformation Stack, I see overall 12 resources and all of them are of type ManagedPolicy or Role - no Firehouse, CloudWatch, EventBridge and so on.

Not sure if I did something wrong or this is a bug of console integration into AWS account.

**Comment by Danwakeem** [comment]
Hey @oddity-code thank you for reporting. We are aware of the issue and we are working on a fix. I will update this ticket when the fix has been released. Thanks again!

**Comment by Danwakeem** [comment]
Hey @oddity-code we just cut a release in our backend systems that have fixed this issue. You should be able to re-instrument your functions via console or the CLI. If you have any other issues with this please feel free to comment on this issue.
